/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(onboarding)'}/cargo` | `/cargo`; params?: Router.UnknownInputParams; } | { pathname: `${'/(onboarding)'}/localizacao` | `/localizacao`; params?: Router.UnknownInputParams; } | { pathname: `${'/(onboarding)'}/reward` | `/reward`; params?: Router.UnknownInputParams; } | { pathname: `${'/(onboarding)'}/salario` | `/salario`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/negociacao` | `/negociacao`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/perfil` | `/perfil`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/resultado` | `/resultado`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/tracker` | `/tracker`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/vagas` | `/vagas`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(onboarding)'}/cargo` | `/cargo`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(onboarding)'}/localizacao` | `/localizacao`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(onboarding)'}/reward` | `/reward`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(onboarding)'}/salario` | `/salario`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/negociacao` | `/negociacao`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/perfil` | `/perfil`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/resultado` | `/resultado`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/tracker` | `/tracker`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/vagas` | `/vagas`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(onboarding)'}/cargo${`?${string}` | `#${string}` | ''}` | `/cargo${`?${string}` | `#${string}` | ''}` | `${'/(onboarding)'}/localizacao${`?${string}` | `#${string}` | ''}` | `/localizacao${`?${string}` | `#${string}` | ''}` | `${'/(onboarding)'}/reward${`?${string}` | `#${string}` | ''}` | `/reward${`?${string}` | `#${string}` | ''}` | `${'/(onboarding)'}/salario${`?${string}` | `#${string}` | ''}` | `/salario${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/negociacao${`?${string}` | `#${string}` | ''}` | `/negociacao${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/perfil${`?${string}` | `#${string}` | ''}` | `/perfil${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/resultado${`?${string}` | `#${string}` | ''}` | `/resultado${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/tracker${`?${string}` | `#${string}` | ''}` | `/tracker${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/vagas${`?${string}` | `#${string}` | ''}` | `/vagas${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(onboarding)'}/cargo` | `/cargo`; params?: Router.UnknownInputParams; } | { pathname: `${'/(onboarding)'}/localizacao` | `/localizacao`; params?: Router.UnknownInputParams; } | { pathname: `${'/(onboarding)'}/reward` | `/reward`; params?: Router.UnknownInputParams; } | { pathname: `${'/(onboarding)'}/salario` | `/salario`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/negociacao` | `/negociacao`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/perfil` | `/perfil`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/resultado` | `/resultado`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/tracker` | `/tracker`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/vagas` | `/vagas`; params?: Router.UnknownInputParams; };
    }
  }
}
